language: node_js
node_js:
  - "16"

install:
  - npm install codecov -g
  - yarn install
  - yarn build

script:
  - yarn ci

after_success:
  - codecov
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push --quiet --set-upstream origin master
  - git checkout master

deploy:
  - provider: script
    script: npx lerna publish --yes --conventional-commits --create-release=github && git push && git push --tags
    skip_cleanup: true
    keep_history: true
    on:
      branch: master

branches:
  only:
    - master
