name: pull-request
on: [pull_request]
jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - name: Install dependencies
              run: yarn
            - name: Build packages
              run: yarn build
            - name: Typescript checks
              run: yarn ts
            - name: ESLint checks
              run: yarn lint
            - name: Find dead code
              run: yarn find-deadcode
            - name: Find copy-paste
              run: yarn cpd
            - name: Unit tests
              run: yarn test:coverage

